version: '3'

services:
  node:
    image: ghcr.io/gear-tech/node
    command: gear-node --dev --tmp -l0 --unsafe-ws-external --unsafe-rpc-external --rpc-methods Unsafe --rpc-cors all
    expose:
      - '9165'
      - '9933'
      - '9944'
      - '30333'

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    expose:
      - '5432'

  backend:
    image: ghcr.io/gear-tech/backend
    depends_on:
      - node
      - postgres
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=postgres
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=test
      - WS_PROVIDER=ws://node:9944
      - ACCOUNT_SEED=e5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a
      - SUDO_SEED=e5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a
      - SITE_ACCOUNT_BALANCE=10000000000

  frontend:
    image: ghcr.io/gear-tech/frontend
    depends_on:
      - backend
    ports:
      - '8080:80'
